version: 2

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
  disable:
    - golint
    - gosec

run:
  timeout: 5m

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
