linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - golint
    - gosec
    - misspell

run:
  timeout: 5m

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
